### ISSUE TITLE
is any event to obtain a selected item?

### ISSUE THREAD

**Issue by VelascoPale** [RedHeadphone/react-json-grid#15]
on https://jsongrid.com/json-parser 
when our selects a value into the grid, it is been selected on json editor, do u use an event to obtain the selected item?

**Comment by RedHeadphone** [comment]
I am not the owner of https://jsongrid.com/. This React component library is just a clone of the UI. But having an event "onSelect" that takes a handler function with the parameter "keyPath" (list of keys that leads to the selected cell) seems a good idea to integrate into this component.

**Comment by RedHeadphone** [comment]
@VelascoPale I have published this feature, you can find it in v0.6.0 on npm. Let me know if you find any issues!
