### ISSUE TITLE
Having a value as null / undefined breaks the component

### ISSUE THREAD

**Issue by essuraj** [RedHeadphone/react-json-grid#16]
instead of .toString().  use String(null)

**Comment by RedHeadphone** [comment]
Can you give more context and exact props that break the component? Also if you know the fix you are open to creating PR for the fix.

**Comment by essuraj** [comment]
any props variety has this issue, eg: https://codesandbox.io/s/react-json-grid-demo-7ymdg3
<img width="1338" alt="image" src="https://github.com/user-attachments/assets/486fafcd-e80f-4954-9d87-da95ab397d61">
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/dd0fc7a9-b580-4f4f-b6e4-f229bd2efe53">

**Comment by RedHeadphone** [comment]
Oh yeah, I don't know how I missed it. Using `String(value)` instead of `value.toString()` is definitely better. Thanks for letting me know.

would you like to fix it?

also on a sidenote which tool are you using to highlight in the screenshot?

**Comment by essuraj** [comment]
https://shottr.cc/
Regards,
*Suraj ES*
